# Generated by Django 5.2.4 on 2025-08-05 07:08

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='claim_type',
            field=models.CharField(choices=[('Auto Insurance', 'Auto Insurance'), ('Home Insurance', 'Home Insurance'), ('Health Insurance', 'Health Insurance'), ('Life Insurance', 'Life Insurance'), ('Travel Insurance', 'Travel Insurance'), ('Business Insurance', 'Business Insurance'), ('Other', 'Other')], db_index=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['claim_type'], name='payments_claim_t_8aeb8e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['scheduled_date', 'claim_type'], name='payments_schedul_e72f55_idx'),
        ),
    ]
