# Generated by Django 5.2.4 on 2025-08-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_claim_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='claim_type',
            field=models.CharField(choices=[('Auto Insurance', 'Auto Insurance'), ('Home Insurance', 'Home Insurance'), ('Health Insurance', 'Health Insurance'), ('Life Insurance', 'Life Insurance'), ('Travel Insurance', 'Travel Insurance'), ('Business Insurance', 'Business Insurance'), ('Other', 'Other')], db_index=True, default='Other', max_length=50),
        ),
    ]
